### ISSUE TITLE
只輸入一個字的情況下，無法顯示結果。

### ISSUE THREAD

**Issue by amowu** [amowu/alfred-chinese-converter#3]
只輸入一個字：

![screen shot 2015-08-06 at 2 11 35 am](https://cloud.githubusercontent.com/assets/559351/9093769/9a921902-3be0-11e5-9ea3-ea67e00f0770.png)

在字後面加一個空隔可以成功：

![screen shot 2015-08-06 at 2 11 55 am](https://cloud.githubusercontent.com/assets/559351/9093800/c3f1a01a-3be0-11e5-88d3-71128157aa0a.png)

**Comment by hanksudo** [comment]
我是一字可以, 兩字不行。OpenCC 1.0.3

<img width="594" alt="screen shot 2016-01-16 at 14 51 39" src="https://cloud.githubusercontent.com/assets/467745/12371016/b212ffa0-bc60-11e5-97da-64cab854fa9e.png">
<img width="594" alt="screen shot 2016-01-16 at 14 51 47" src="https://cloud.githubusercontent.com/assets/467745/12371017/b2190b34-bc60-11e5-889e-11c8bfa7e97e.png">

**Comment by fcwork** [comment]
输入两个字时出错
OpenCC 1.0.4
macOS Mojave 10.14.1
Alfred 3.7.1 调试模式的错误代码如下
```
Starting debug for 'Chinese Converter'

[2018-12-19 11:09:26][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "chineseconverter.py", line 49, in <module>
    process(query_str)
  File "chineseconverter.py", line 9, in process
    xml = alfred.xml(results) # compiles the XML answer
  File "/Users/xxxxxxxxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.D034703D-1AC5-41A4-843B-74EC19E0DE87/alfred.py", line 85, in xml
    root.append(item.xml())
  File "/Users/xxxxxxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.D034703D-1AC5-41A4-843B-74EC19E0DE87/alfred.py", line 52, in xml
    SubElement(item, attribute, self.unicode(attributes)).text = unicode(value)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 528, in SubElement
    attrib = attrib.copy()
AttributeError: 'unicode' object has no attribute 'copy'
```
图片
<img width="1221" alt="screen shot 2018-12-19 at 11 09 40" src="https://user-images.githubusercontent.com/43286431/50196970-42a02700-0380-11e9-9bf1-7a5b66030bcc.png">
